name: SurgeX Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SurgeX
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
       run: ./gradlew :app:assembleDebug --stacktrace -Dorg.gradle.jvmargs="-Xmx2048m" 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SurgeX-debug
          path: app/build/outputs/apk/debug/*.apk
